W5 DynamoDB utility part 3

diff --git a/backend-flask/bin/ddb/drop b/backend-flask/bin/ddb/drop
--- a/backend-flask/bin/ddb/drop
+++ b/backend-flask/bin/ddb/drop
@@ -1,1 +1,29 @@
-#
+#! /usr/bin/bash
+set -e # stop if it fails at any point
+
+CYAN='\033[1;36m'
+NO_COLOR='\033[0m'
+LABEL="Drop"
+printf "${CYAN}== ${LABEL}${NO_COLOR}\n"
+
+# ./db/ddb/drop cruddur-messages prod
+
+#Check if the conection URL is prod or dev
+if [ -z "$1" ]; then
+    echo "No TABLE_NAME argument supplied eg ./db/ddb/drop cruddur-messages prod"
+    exit 1
+fi
+
+TABLE_NAME=$1
+
+if [ "$2" = "prod" ]; then
+    ENDPOINT_URL=""
+else
+    ENDPOINT_URL="--endpoint-url=http://localhost:8000"
+fi
+
+echo "Deleting table: $TABLE_NAME"
+
+#get the list of tables via AWS command
+aws dynamodb delete-table $ENDPOINT_URL \
+--table-name $TABLE_NAME
